#if UNITY_EDITOR

using System.Globalization;
using System.Text;
using SnivelerCode.GpuAnimation.Editor.Utils;

namespace SnivelerCode.GpuAnimation.Editor.Window
{
    public sealed class CodeGenerator : ICodeGenerator
    {
        public string GenerateParamsCode(PrefabInstance instance, string[] anims, string namespaceName)
        {
            var cb = new AnimatorCodeBuilder();
            cb.Line("//------------------------------------------------------------------------------");
            cb.Line("// <auto-generated>");
            cb.Line("//     This code was generated by Animator.");
            cb.Line("//     IDs are generated automatically from your Animator Project.");
            cb.Line("// </auto-generated>");
            cb.Line("//------------------------------------------------------------------------------");
            cb.Line();

            cb.Line("using System.Collections.Generic;");
            cb.Line("using SnivelerCode.GpuAnimation.Runtime.Components;");
            cb.Line();

            using (cb.Block($"namespace {namespaceName}"))
            {
                using (cb.Block($"public static class Animator{instance.Name}"))
                {
                    for (int i = 0; i < anims.Length; i++)
                    {
                        cb.Line($"public static readonly byte {anims[i]} = {i};");
                    }
                }

                using (cb.Block("public static partial class AnimatorParams"))
                {
                    using (cb.Block($"public static class {instance.Name}"))
                    {
                        for (byte i = 0; i < instance.Parameters.Count; i++)
                        {
                            string paramName = ToCamelCase(instance.Parameters[i].Name);
                            cb.Line($"public static readonly byte {paramName} = {i};");
                        }
                    }
                }
            }

            return cb.ToString();
        }

        public static string ToCamelCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;

            StringBuilder result = new StringBuilder();
            bool nextUpper = true;

            foreach (char c in input)
            {
                if (char.IsLetterOrDigit(c))
                {
                    result.Append(nextUpper ? char.ToUpper(c, CultureInfo.InvariantCulture) : c);
                    nextUpper = false;
                }
                else
                {
                    nextUpper = true;
                }
            }

            return result.ToString();
        }
    }
}

#endif
